site_name: Product Security Handbook
site_url: https://schmitthub.github.io/prodsec-handbook/
nav:
  - Home: index.md
  - Architecture:
      - architecture/index.md
      - Micro Services: architecture/microservices.md
      - Patterns:
          - Backends For Frontends: architecture/bff.md
  - Auth:
      - auth/index.md
      - Token Security: auth/token_security.md
  - Code Security:
      - code-security/index.md
      - Commit Signing: code-security/commit_signing.md
  - Resources:
      - resources/index.md
      - Books: resources/books.md
      - Web: resources/web.md
  - Threat Modeling: threat_modeling.md

theme:
  features:
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  name: material

repo_name: schmitthub/prodsec-handbook
repo_url: https://github.com/schmitthub/prodsec-handbook

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - privacy
  - search
  - tags
