site_name: Learn ProdSec
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Code Security:
      - Commit Signing: commit_signing.md
  - Study Materials: study_materials.md
  - Threat Modeling: threat_modeling.md
theme:
  name: material

repo_name: ajschmitty/prodsec-interview-prep
repo_url: https://github.com/ajschmitty/learn-prodsec

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
